name: Build & Deploy DEV

on:
  push:
    branches:
      - dev

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Забираем код
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: web/package-lock.json


      # 3️⃣ Установка зависимостей (web)
      - name: Install dependencies (web)
        working-directory: web
        run: npm ci --legacy-peer-deps

      # 4️⃣ Build (web)
      - name: Build web
        working-directory: web
        env:
          CI: true
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_APP_ID: ${{ secrets.REACT_APP_APP_ID }}
          REACT_APP_VAPID_KEY: ${{ secrets.REACT_APP_VAPID_KEY }}
        run: npm run build

      # 5️⃣ Deploy build/ на сервер
      - name: Upload build to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          source: "web/build/**"
          target: /var/www/dev.chatpwa.ru/web/build
          strip_components: 2

      - name: Upload backend
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          source: "server/server.js"
          target: /var/www/dev.chatpwa.ru/server
          strip_components: 1   # убирает лишнюю вложенность


      # 6️⃣ Перезапуск сервера (без билда)
      - name: Restart backend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/dev.chatpwa.ru/server
            npm install --legacy-peer-deps
            pm2 restart chatpwa-dev || pm2 start server.js --name chatpwa-dev --watch
            pm2 save
